### ISSUE TITLE
Wrong coding example

### ISSUE THREAD

**Issue by kadnan** [mbarkhau/tinypng#2]
I kept trying `from tinypng import shrink_file` and was getting error. On investigation it figured out that it would be like that:

```
from tinypng import api
API_KEY = ''

# implicitly writes to "your_file.tiny.png"
shrink_info = api.shrink_file("Sample.png", api_key=API_KEY)
```

**Comment by mbarkhau** [comment]
Thanks for the bug report, I'll look into it later today.
